export const RECOVERY_PLAN_REPOSITORY = Symbol('RECOVERY_PLAN_REPOSITORY');
export const EXERCISE_REPOSITORY = Symbol('EXERCISE_REPOSITORY');
export const EXERCISE_LOG_REPOSITORY = Symbol('EXERCISE_LOG_REPOSITORY');
export const APPOINTMENT_REPOSITORY = Symbol('APPOINTMENT_REPOSITORY');
export const MEASUREMENT_REPOSITORY = Symbol('MEASUREMENT_REPOSITORY');
export const PROGRESS_PHOTO_REPOSITORY = Symbol('PROGRESS_PHOTO_REPOSITORY');
export const EXERCISE_COMPLETION_REPOSITORY = Symbol(
  'EXERCISE_COMPLETION_REPOSITORY',
);
export const PAIN_LOG_REPOSITORY = Symbol('PAIN_LOG_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
